uploads = []
generated = []

[[outputs]]
id = "29YCAx9-squIxKOqZU676"
uri = "file://Vickery-PO-System-Training-Guide.md"
type = "text"
title = "Vickery PO System — Training Guide"

[[outputs]]
id = "NJ96eX6NNk_pQMWzDV0wa"
uri = "file://vickery-db-backup-20260505_121357.dump.gz"
type = "unspecified"
title = "vickery-db-backup-20260505_121357.dump.gz"

[[outputs]]
id = "TpHL9Av7hoYyO8QY4LbQq"
uri = "file://vickery-db-export-20260711.zip"
type = "unspecified"
title = "Vickery DB Export — July 11, 2026"
