import { Router, type IRouter } from "express";
import healthRouter from "./health";
import storageRouter from "./storage";
import authRouter from "./auth";
import usersRouter from "./users";
import priceImportRouter from "./price-import";
import vendorsRouter from "./vendors";
import ordersRouter from "./orders";
import summaryRouter from "./summary";
import vendorConfirmRouter from "./vendor-confirm";
import inventoryRouter from "./inventory";
import settingsRouter from "./settings";
import salesOrdersRouter from "./sales-orders";
import reportsRouter from "./reports";
import shopAvailabilityRouter from "./shop-availability";
import shopOrderItemsRouter from "./shop-order-items";
import customersRouter from "./customers";
import customerAuthRouter from "./customer-auth";

const router: IRouter = Router();

router.use(healthRouter);
router.use(storageRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(priceImportRouter);
router.use(vendorsRouter);
router.use(ordersRouter);
router.use(summaryRouter);
router.use(vendorConfirmRouter);
router.use(inventoryRouter);
router.use(settingsRouter);
router.use(salesOrdersRouter);
router.use(reportsRouter);
router.use(shopAvailabilityRouter);
router.use(shopOrderItemsRouter);
router.use(customersRouter);
router.use(customerAuthRouter);

export default router;
